---
# This workflow runs all of the very-long tests within main.py

name: Weekly Tests

on:
    # This is triggered weekly via the 'scheduler.yaml' workflow.
    workflow_dispatch:

jobs:

    get-date:
        runs-on: ubuntu-24.04
        outputs:
            date: ${{ steps.date.outputs.date }}
        steps:
            - name: Get the current date
              id: date
              run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

  # this builds and runs unittests.fast, opt, and debug
    unittests-fast-opt-debug:
        strategy:
            matrix:
                type: [fast, opt, debug]
        runs-on: ubuntu-24.04
        container: ghcr.io/gem5/ubuntu-24.04_all-dependencies:latest
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@v4

            - name: Run ALL/unittests.${{ matrix.type }} UnitTests
              run: scons build/ALL/unittests.${{ matrix.type }} -j --gcov $(nproc)

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  flags: unittests-${{ matrix.type }}

    # get TestLib test directories for quick, long, and very-long tests
    get-testlib-dirs:
        strategy:
            matrix:
                type: [quick, long, very-long]
        runs-on: ubuntu-24.04
        container: ghcr.io/gem5/ubuntu-24.04_all-dependencies:latest
        outputs:
            # test-dirs-matrix: [{length: quick, testdir: '${{ steps.dir-matrix.outputs.test-dirs-matrix-quick }}'}, {length: long, testdir: '${{ steps.dir-matrix.outputs.test-dirs-matrix-long
                          # }}'}, {length: very-long, testdir: '${{ steps.dir-matrix.outputs.test-dirs-matrix-very-long }}'}]

            test-dirs-matrix-quick: ${{ steps.dir-matrix.outputs.test-dirs-matrix-quick }}
            test-dirs-matrix-long: ${{ steps.dir-matrix.outputs.test-dirs-matrix-long }}
            test-dirs-matrix-very-long: ${{ steps.dir-matrix.outputs.test-dirs-matrix-very-long }}
        steps:
            - uses: actions/checkout@v4
            - name: Get directories for testlib-very-long
              working-directory: ${{ github.workspace }}/tests
              id: dir-matrix
              run: |
                  unset PREV
                  echo "test-dirs-matrix-${{ matrix.type }}=$(\
                    ./main.py list gem5 \
                    --suites \
                    --length ${{ matrix.type }} \
                    --gcov=test-only \
                    --exclude-tags gcn_gpu | \
                    grep "$SUITEUID:" | \
                    cut -d: -f2 | \
                    cut -d/ -f 2- | \
                    xargs dirname | \
                    sort -u  | \
                    while read x; do \
                      if [ -z "${PREV}" ] || [ "$x" != "${PREV}/*" ]; then \
                        PREV=$x; \
                        echo $x; \
                      fi; \
                    done  | \
                    jq -ncR '[inputs]'\
                  )" >>$GITHUB_OUTPUT

    match-length-and-test-matrix:
        name: match-length-and-test-matrix
        strategy:
            matrix:
                type: [quick, long, very-long]
        runs-on: ubuntu-24.04
        container: ghcr.io/gem5/ubuntu-24.04_all-dependencies:latest
        outputs:
            test-dirs-matrix-flattened: ${{ steps.flatten-matrix.outputs.matrix }}
        steps:
            - id: flatten-matrix
              run: |
                  primary='["quick", "long", "very-long"]'
                  secondary='{
                      "quick": ${{ fromJson(needs.get-testlib-dirs.outputs.test-dirs-matrix-quick) }},
                      "long": ${{ fromJson(needs.get-testlib-dirs.outputs.test-dirs-matrix-long) }},
                      "very-long": ${{ fromJson(needs.get-testlib-dirs.outputs.test-dirs-matrix-very-long) }},
                  }'

                  flat_matrix=$(echo $secondary | jq -c '[
                    to_entries[] |
                    .key as $k |
                    .value[] |
                    {length: $k, testdir: .}
                  ]')

                  echo "matrix=$flat_matrix" >> $GITHUB_OUTPUT

    # start running the very-long tests
    testlib-tests:
        name: testlib-tests
        strategy:
            fail-fast: false
            matrix:
                test-type: ${{ fromJson(needs.match-length-and-test-matrix.outputs.test-dirs-matrix-flattened) }}
                # type: [quick, long, very-long]
                # test-type: ${{ fromJson(needs.get-testlib-dirs.outputs.test-dirs-matrix-${{ matrix.type }}) }}
                # type: [{length: quick, testdir: '${{fromJson(needs.get-testlib-dirs.outputs.test-dirs-matrix-quick)}}'}, {length: long, testdir: '${{fromJson(needs.get-testlib-dirs.outputs.test-dirs-matrix-long)}}'}, {length: very-long, testdir: '${{fromJson(needs.get-testlib-dirs.outputs.test-dirs-matrix-very-long)}}'}]
        runs-on: ubuntu-24.04
        container: ghcr.io/gem5/ubuntu-24.04_all-dependencies:latest
        timeout-minutes: 4320 # 3 days
        needs: [get-date, get-testlib-dirs, match-length-and-test-matrix]
        steps:
            - uses: actions/checkout@v4

            - name: Cache build/ALL
              uses: actions/cache@v4
              with:
                  path: build/ALL
                  key: testlib-build-all-${{ needs.get-date.outputs.date }}
                  restore-keys: |
                      testlib-build-all

            - name: Run ${{ matrix.type }} ${{ matrix.test-type }} tests
              id: run-tests
              working-directory: ${{ github.workspace }}/tests
              run: ./main.py run ${{ matrix.test-type.testdir }} --length ${{ matrix.test-type.length }} -j$(nproc) -vv --exclude-tags gcn_gpu

            - name: Sanitize test-dir for artifact name
              id: sanitize-test-dir
              if: success() || failure()
              run: echo "sanitized-test-dir=$(echo '${{ matrix.test-type.testdir }}' | sed 's/\//-/g')" >> $GITHUB_OUTPUT

            - name: Upload results
              if: success() || failure()
              uses: actions/upload-artifact@v4
              with:
                  name: weekly-tests-run-${{ github.run_number }}-attempt-${{ github.run_attempt }}-testlib-very-long-${{ steps.sanitize-test-dir.outputs.sanitized-test-dir
                      }}-status-${{ steps.run-tests.outcome }}-output
                  path: tests/testing-results

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  flags: ['${{steps.sanitize-test-dir.outputs.sanitized-test-dir}}', '${{matrix.test-type.length}}']

    gpu-tests:
        runs-on: ubuntu-24.04
        container: ghcr.io/gem5/gcn-gpu:latest
        timeout-minutes: 1440 # 24 hours
        needs: get-date

        steps:
            - uses: actions/checkout@v4

            - name: Cache build/VEGA_X86
              uses: actions/cache@v4
              with:
                  path: build/VEGA_X86
                  key: testlib-build-vega-${{ needs.get-date.outputs.date }}
                  restore-keys: |
                      testlib-build-vega

            - name: Run Testlib GPU Tests
              id: run-tests
              working-directory: ${{ github.workspace }}/tests
              run: ./main.py run --length=very-long -vvv -j $(nproc) --host gcn_gpu

            - name: Upload results
              if: success() || failure()
              uses: actions/upload-artifact@v4
              with:
                  name: weekly-tests-run-${{ github.run_number }}-attempt-${{ github.run_attempt }}-gpu-status-${{ steps.run-tests.outcome }}-output
                  path: tests/testing-results
